Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DataRoadAnalyticsLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DataRoadS3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::dev-raw-analytics
                  - arn:aws:s3:::dev-raw-analytics/*
  DataRoadAnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DataRoadAnalytics
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      CodeUri: ./
      MemorySize: 512
      Timeout: 900
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          dev_mode: true
          custom_app_type: transaction
          custom_app_process_stage: extractor
          bucket_name: dev-raw-analytics
          bucket_prefix: raw-data/data-raw/
